name: Publish Web Release

on:
  push:
    tags:        
      - '*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
  
      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Make gradlew executable
        run: chmod +x ./gradlew
  
      - name: Run wasmJsBrowserDistribution task
        run: ./gradlew wasmJsBrowserDistribution

      - name: Backup production files
        run: |
          mkdir -p /tmp/productionExecutable
          cp -R compose-app/build/dist/wasmJs/productionExecutable/* /tmp/productionExecutable/

      - name: Update web branch with production executable files
        run: |
          # Configure Git identity
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

          # Fetch and check out (or create) the web branch
          git fetch origin web || true
          git checkout -B web

          # Remove all files (except .git) to ensure a clean branch
          find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +

          # Copy the production files from the temporary backup folder into the repository root
          cp -R /tmp/productionExecutable/* .

          # Stage, commit, and force-push the changes using the tag name as the commit message
          git add .
          git commit -m "${{ github.ref_name }}"
          git push -f origin web